### ISSUE TITLE
does not work with laravel 7

### ISSUE THREAD

**Issue by firecentaur** [jalangle/laravel-usercli#2]
Hi there, tried to install:

Installation request for laravel/framework (locked at v7.15.0, required as ^7.0) -> satisfiable by laravel/framework[v7.15.0].

**Comment by jalangle** [comment]
Sorry it took so long to respond.  Should work now with v0.0.8.  I mostly use this for just myself off dev-master and it was at least installing/enumeration off that on laravel7.

If you try again and it doesn't work, please ping again.
